const ALL_TOPICS = {
  React: [
    "Components",
    "State",
    "Props",
    "Hooks",
    "Event Handling",
    "Router",
    "Testing",
    "App Building",
    "Forms",
    "Lifecycle Methods",
    "Conditional Rendering",
  ],
  Javascript: [
    "Variables",
    "Data Types",
    "Functions",
    "Promises",
    "ES6",
    "Objects",
    "Events",
    "Arrays",
    "DOM Manipulation",
    "Error Handling",
    "JSON Handling",
  ],
  Node: [
    "NPM",
    "Express",
    "Middleware",
    "Routing",
    "File System",
    "Events",
    "Debugging",
    "Async Programming",
    "Creating a Simple Node App",
    "RESTful APIs",
    "Authentication",
    "Database Integration",
    "GraphQL",
    "Real-time WebSockets",
    "Security Best Practices",
  ],
  CSS: [
    "Selectors",
    "Box Model",
    "Flexbox",
    "Grid",
    "Typography",
    "Colors",
    "Transitions",
    "Animations",
    "Responsive Design",
    "Frameworks",
    "Preprocessors",
  ],
  Git: [
    "Repository",
    "Commits",
    "Branching",
    "Merging",
    "Remote",
    "Pull Requests",
    "Rebase",
    "Git ignore",
    "Version Control",
    "Conflict Resolution",
    "Git Workflow",
    "Git Hooks",
  ],
  HTML: [
    "HTML Document Structure",
    "Lists",
    "Links",
    "Images",
    "Forms",
    "Tables",
    "Semantic HTML",
    "Multimedia",
    "HTML Entities",
    "HTML Comments",
    "Attributes",
    "HTML Validation",
    "HTML5 Features",
    "HTML Best Practices",
  ],
};

export default ALL_TOPICS;
