const ALL_TOPICS = {
  React: [
    "ReactJS",
    "Components",
    "State",
    "Props",
    "Hooks",
    "EventHandling",
    "Router",
    "Styling",
    "Testing",
    "AppBuilding",
    "Forms",
    "LifecycleMethods",
    "ConditionalRendering",
  ],
  Javascript: [
    "JavaScript",
    "Variables",
    "DataTypes",
    "Functions",
    "Promises",
    "ES6",
    "Objects",
    "Events",
    "Arrays",
    "Webpack",
    "DOMManipulation",
    "ErrorHandling",
    "JSONHandling",
  ],
  Node: [
    "NodeJS",
    "NPM",
    "Express",
    "Middleware",
    "Routing in Node",
    "File System",
    "Events in Node",
    "Debugging in Node",
    "Async Programming",
    "Creating a Simple Node App",
    "RESTfulAPIs",
    "Authentication in Node",
    "DatabaseIntegration",
    "GraphQL in Node",
    "Real-time WebSockets",
    "Security Best Practices in Node",
  ],
  CSS: [
    "CSS",
    "Selectors",
    "BoxModel",
    "Flexbox",
    "Grid",
    "Typography",
    "Colors",
    "Transitions",
    "Animations",
    "ResponsiveDesign",
    "Frameworks",
    "Preprocessors",
    "BEMMethodology",
  ],
  GIT: [
    "Git",
    "Repository",
    "Commits",
    "Branching",
    "Merging",
    "Remote",
    "PullRequest",
    "Rebase",
    "Gitignore",
    "VersionControl",
    "ConflictResolution",
    "GitWorkflow",
    "GitHooks",
  ],
};

export default ALL_TOPICS;
