const  ALL_TOPICS = {
  react: [
    'ReactJS',
    'Components',
    'State',
    'Props',
    'Hooks',
    'EventHandling',
    'Router',
    'Styling',
    'Testing',
    'AppBuilding',
    'Forms',
    'LifecycleMethods',
    'ConditionalRendering',
  ],
  javascript: [
    'JavaScript',
    'Variables',
    'DataTypes',
    'Functions',
    'Promises',
    'ES6',
    'Objects',
    'Events',
    'Arrays',
    'Webpack',
    'DOMManipulation',
    'ErrorHandling',
    'JSONHandling',
  ],
  node: [
    'NodeJS',
    'NPM',
    'Express',
    'Middleware',
    'Routing in Node',
    'File System',
    'Events in Node',
    'Debugging in Node',
    'Async Programming',
    'Creating a Simple Node App',
    'RESTfulAPIs',
    'Authentication in Node',
    'DatabaseIntegration',
    'GraphQL in Node',
    'Real-time WebSockets',
    'Security Best Practices in Node',
  ],
  css: [
    'CSS',
    'Selectors',
    'BoxModel',
    'Flexbox',
    'Grid',
    'Typography',
    'Colors',
    'Transitions',
    'Animations',
    'ResponsiveDesign',
    'Frameworks',
    'Preprocessors',
    'BEMMethodology',
  ],
  git: [
    'Git',
    'Repository',
    'Commits',
    'Branching',
    'Merging',
    'Remote',
    'PullRequest',
    'Rebase',
    'Gitignore',
    'VersionControl',
    'ConflictResolution',
    'GitWorkflow',
    'GitHooks',
  ],
};

export default ALL_TOPICS;
